### PR TITLE
Classification_by_decision_tree.py

### PR DESCRIPTION
**Pull request by RuizGeo**

### CODE REVIEW

**Comment by alexbruy** [comment]
May I ask you to add help for this script?

**Comment by RuizGeo** [comment]
Hy,
I added the help file on github.
thank you

2015-03-05 11:41 GMT-03:00 alexbruy <notifications@github.com>:

> May I ask you to add help for this script?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qgis/QGIS-Processing/pull/4#issuecomment-77374678>.
>



-- 
Luis Fernando Chimelo Ruiz
Técnico em Geomensura - CREA - RS: 168.208
Tecnólogo em Geoprocessamento
Mestrando em Sensoriamento Remoto na UFRGS

**Comment by pcav** [comment]
Thanks Ruiz! @volaya @alexbruy better merge it?

**Comment by RuizGeo** [comment]
Yes, no problem.
thanks.

2015-03-10 16:39 GMT-03:00 Paolo Cavallini <notifications@github.com>:

> Thanks Ruiz! @volaya <https://github.com/volaya> @alexbruy
> <https://github.com/alexbruy> better merge it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qgis/QGIS-Processing/pull/4#issuecomment-78131508>.
>



-- 
Luis Fernando Chimelo Ruiz
Técnico em Geomensura - CREA - RS: 168.208
Tecnólogo em Geoprocessamento
Mestrando em Sensoriamento Remoto na UFRGS

**Comment by RuizGeo** [comment]
Hi,
Could you tell me how to Merge?
Thank

2015-03-10 16:42 GMT-03:00 Luis Fernando Chimelo Ruiz <ruiz.ch@gmail.com>:

> Yes, no problem.
> thanks.
>
> 2015-03-10 16:39 GMT-03:00 Paolo Cavallini <notifications@github.com>:
>
>> Thanks Ruiz! @volaya <https://github.com/volaya> @alexbruy
>> <https://github.com/alexbruy> better merge it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/qgis/QGIS-Processing/pull/4#issuecomment-78131508>.
>>
>
>
>
> --
> Luis Fernando Chimelo Ruiz
> Técnico em Geomensura - CREA - RS: 168.208
> Tecnólogo em Geoprocessamento
> Mestrando em Sensoriamento Remoto na UFRGS
>



-- 
Luis Fernando Chimelo Ruiz
Técnico em Geomensura - CREA - RS: 168.208
Tecnólogo em Geoprocessamento
Mestrando em Sensoriamento Remoto na UFRGS

**Pull request merged**
