### PR TITLE
fixed VectorWriter import

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by slarosa** [comment]
@anitagraser Why are there 19 separate pull requests?

**Comment by anitagraser** [comment]
Because I started editing on Github and didn't expect that I'd be changing so many files ...

**Comment by slarosa** [comment]
@anitagraser no problem I squashed and pulled in 425a940. Could you check the commit if any thing is fine there? I would not have missed something.

**Comment by anitagraser** [comment]
@slarosa Thanks, looks perfect!

**Pull request closed without merging**
