### PR TITLE
[processing] Add Batch export layers script

### PR DESCRIPTION
**Pull request by mdouchin**

### CODE REVIEW

**Comment by luipir** [comment]
@nyalldawson have to be considered this PR as a new feature?

**Comment by mdouchin** [comment]
This repository used to be kind of independant of QGIS repo, to allow users (not only devs) to share some useful scripts. I really see this repo like the plugins.qgis.org, with contributed plugins. 

IMHO new scripts should be possible here. Please do not forget thant QGIS 2.18 is the actual LTR, used in production by many users, until next LTR 3.4.4 (in February 2019 ).

**Comment by luipir** [comment]
@mdouchin ouch my fault

**Comment by mdouchin** [comment]
gentle ping @luipir @nyalldawson 
Please note this is a handy tool in 2.18 to export all chosen layers into a single Geopackage file (or Shapefiles) without the need to run the batch mode, which can be cumbersome for some users (seen during courses).

I could add a reproject option and more export formats, but I would like to keep it kiss

**Comment by nyalldawson** [comment]
Does feature freeze even apply here? I don't think it does for this repo.

**Comment by luipir** [comment]
houch... sorry again, I missed this notification @mdouchin. I can't if it's necessary to add more options, I leave you to add more in further PRs.

**Comment by mdouchin** [comment]
thanks !

**Pull request merged**
