### PR TITLE
New algorithms for vector and raster processing

### PR DESCRIPTION
**Pull request by samuel-rosa**
* Convert the data type of selected fields of a vector attribute table
* Create and add an attribute table to a raster layer

### CODE REVIEW

**Comment by samuel-rosa** [comment]
new function that creates a bar plot with vertical bars using `barplot()`

**Comment by alexbruy** [comment]
> Convert the data type of selected fields of a vector attribute table

Maybe I miss something but this functionality already available with Field Mapper algorithm

**Comment by samuel-rosa** [comment]
I was unaware of the Field Mapper algorithm. Where is it available? Under the Processing Toolbox?

**Comment by samuel-rosa** [comment]
By 'Field Mapper' did you mean 'Refactor Fields'? If so, then I see that **my algorithm is redundant**. But 'Refactor Fields' is poorly documented and would likely be better to name it as 'Field Mapper'.

**Comment by samuel-rosa** [comment]
I removed the redundant algorithm.

**Comment by samuel-rosa** [comment]
Do you think this pull request can be merged?

**Pull request merged**
